// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEiKdEFKganbbqZ4pnJOs-lJ_o6qsrcd8',
    appId: '1:377996188370:web:a5b3b5f7c90bbb6c792b0b',
    messagingSenderId: '377996188370',
    projectId: 'parkin-c62bb',
    authDomain: 'parkin-c62bb.firebaseapp.com',
    storageBucket: 'parkin-c62bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkYfFyWDFV6VsWYLnO27NeQkRn1PAZtr8',
    appId: '1:377996188370:android:fce69e957f751940792b0b',
    messagingSenderId: '377996188370',
    projectId: 'parkin-c62bb',
    storageBucket: 'parkin-c62bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeg-S0zEPOBRpT_VfYKTxGamrZMZmTSCM',
    appId: '1:377996188370:ios:d98bffc04a89192d792b0b',
    messagingSenderId: '377996188370',
    projectId: 'parkin-c62bb',
    storageBucket: 'parkin-c62bb.appspot.com',
    iosClientId: '377996188370-c2db790iugge00g3lenop9982qngi7dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
