// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6_MJCzfO2aSdzMpr8KVXKqZ2Q7-ckoE4',
    appId: '1:245975142527:web:eea60f82baac4666562f4a',
    messagingSenderId: '245975142527',
    projectId: 'parkin-73bee',
    authDomain: 'parkin-73bee.firebaseapp.com',
    storageBucket: 'parkin-73bee.appspot.com',
    measurementId: 'G-317GKBSNXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5jozSf50a47ntiSBedyWsRPbyB5-4t8U',
    appId: '1:245975142527:android:086c8cb71aa5cd7e562f4a',
    messagingSenderId: '245975142527',
    projectId: 'parkin-73bee',
    storageBucket: 'parkin-73bee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOV-nJxFgewL6w8zh65gWQwSviLKw3Pgw',
    appId: '1:245975142527:ios:67d58c38213690c8562f4a',
    messagingSenderId: '245975142527',
    projectId: 'parkin-73bee',
    storageBucket: 'parkin-73bee.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
